In [2]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv(r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\cleaned_retail.csv")
segments = pd.read_csv(r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\customer_segments.csv")
churn = pd.read_csv(r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\customer_churn.csv")
forecast = pd.read_csv(r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\revenue_forecast.csv")

In [4]:
print("Retail Columns:")
print(retail.columns)

print("\nSegments Columns:")
print(segments.columns)

print("\nChurn Columns:")
print(churn.columns)

Retail Columns:
Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'Revenue'],
      dtype='object')

Segments Columns:
Index(['Customer ID', 'Recency', 'Frequency', 'Monetary', 'Cluster',
       'Segment'],
      dtype='object')

Churn Columns:
Index(['Customer ID', 'Recency', 'Frequency', 'Monetary', 'Churn',
       'Churn_Prediction'],
      dtype='object')

In [5]:
retail['InvoiceDate'] = pd.to_datetime(
    retail['InvoiceDate']
)

In [6]:
retail['Year'] = retail['InvoiceDate'].dt.year

retail['Month'] = retail['InvoiceDate'].dt.month

retail['Month_Name'] = retail['InvoiceDate'].dt.month_name()

retail['Quarter'] = retail['InvoiceDate'].dt.quarter

retail['Day'] = retail['InvoiceDate'].dt.day

retail['Weekday'] = retail['InvoiceDate'].dt.day_name()

retail['Weekend_Flag'] = retail['Weekday'].isin(
    ['Saturday', 'Sunday']
)

In [7]:
retail['Revenue_Category'] = pd.cut(
    retail['Revenue'],
    bins=[0,50,200,1000,100000],
    labels=[
        'Low',
        'Medium',
        'High',
        'Premium'
    ]
)

In [8]:
retail = retail.merge(
    segments[['Customer ID', 'Segment']],
    on='Customer ID',
    how='left'
)

In [9]:
retail[['Customer ID','Segment']].head()

   Customer ID  Segment
0      13085.0  Regular
1      13085.0  Regular
2      13085.0  Regular
3      13085.0  Regular
4      13085.0  Regular

In [10]:
retail = retail.merge(
    churn[['Customer ID', 'Churn']],
    on='Customer ID',
    how='left'
)

In [11]:
retail[['Customer ID','Churn']].head()

   Customer ID  Churn
0      13085.0      1
1      13085.0      1
2      13085.0      1
3      13085.0      1
4      13085.0      1

In [12]:
retail['Churn_Status'] = retail['Churn'].map({
    0: 'Active',
    1: 'At Risk'
})

In [13]:
retail['Inventory_Risk'] = np.where(
    retail['Quantity'] < 5,
    'High Risk',
    'Low Risk'
)

In [14]:
retail['Order_Size'] = pd.cut(
    retail['Revenue'],
    bins=[0,100,500,1000,100000],
    labels=[
        'Small',
        'Medium',
        'Large',
        'Bulk'
    ]
)

In [15]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805549 entries, 0 to 805548
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Invoice           805549 non-null  int64
 1   StockCode         805549 non-null  object
 2   Description       805549 non-null  object
 3   Quantity          805549 non-null  int64
 4   InvoiceDate       805549 non-null  datetime64[ns]
 5   Price             805549 non-null  float64
 6   Customer ID       805549 non-null  float64
 7   Country           805549 non-null  object
 8   Revenue           805549 non-null  float64
 9   Year              805549 non-null  int32
 10  Month             805549 non-null  int32
 11  Month_Name        805549 non-null  object
 12  Quarter           805549 non-null  int32
 13  Day               805549 non-null  int32
 14  Weekday           805549 non-null  object
 15  Weekend_Flag      805549 non-null  bool
 16  Revenue_Category  805548 non-null  category
 17  Segment           805549 non-null  object
 18  Churn             805549 non-null  int64
 19  Churn_Status      805549 non-null  object
 20  Inventory_Risk    805549 non-null  object
 21  Order_Size        805548 non-null  category
dtypes: bool(1), category(2), datetime64[ns](1), float64(3), int32(4), int64(3), object(8)
memory usage: 106.8+ MB

In [16]:
retail.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,...,Quarter,Day,Weekday,Weekend_Flag,Revenue_Category,Segment,Churn,Churn_Status,Inventory_Risk,Order_Size
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,...,4,1,Tuesday,False,Medium,Regular,1,At Risk,Low Risk,Small
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,...,4,1,Tuesday,False,Medium,Regular,1,At Risk,Low Risk,Small
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,...,4,1,Tuesday,False,Medium,Regular,1,At Risk,Low Risk,Small
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,...,4,1,Tuesday,False,Medium,Regular,1,At Risk,Low Risk,Medium
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,...,4,1,Tuesday,False,Low,Regular,1,At Risk,Low Risk,Small

In [17]:
retail.shape

(805549, 22)

In [18]:
retail.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country',
 'Revenue',
 'Year',
 'Month',
 'Month_Name',
 'Quarter',
 'Day',
 'Weekday',
 'Weekend_Flag',
 'Revenue_Category',
 'Segment',
 'Churn',
 'Churn_Status',
 'Inventory_Risk',
 'Order_Size']

In [19]:
dashboard = retail.merge(
    segments[
        [
            "Customer ID",
            "Recency",
            "Frequency",
            "Monetary",
            "Cluster",
            "Segment"
        ]
    ],
    on="Customer ID",
    how="left"
)

dashboard = dashboard.merge(
    churn[
        [
            "Customer ID",
            "Churn",
            "Churn_Prediction"
        ]
    ],
    on="Customer ID",
    how="left"
)

In [21]:
print(dashboard.columns.tolist())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Revenue', 'Year', 'Month', 'Month_Name', 'Quarter', 'Day', 'Weekday', 'Weekend_Flag', 'Revenue_Category', 'Segment_x', 'Churn_x', 'Churn_Status', 'Inventory_Risk', 'Order_Size', 'Recency', 'Frequency', 'Monetary', 'Cluster', 'Segment_y', 'Churn_y', 'Churn_Prediction']

In [22]:
dashboard = dashboard.drop(columns=["Segment_x", "Churn_x"])

dashboard = dashboard.rename(columns={
    "Segment_y": "Segment",
    "Churn_y": "Churn"
})

In [23]:
import pandas as pd

df = pd.read_csv(r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\dashboard_dataset.csv")

print(df["Churn"].unique())
print(df["Churn_Prediction"].unique())

[1 0]
[1 0]

In [24]:
print(df[["Customer ID", "Monetary"]].head(10))

   Customer ID  Monetary
0      13085.0   2433.28
1      13085.0   2433.28
2      13085.0   2433.28
3      13085.0   2433.28
4      13085.0   2433.28
5      13085.0   2433.28
6      13085.0   2433.28
7      13085.0   2433.28
8      13085.0   2433.28
9      13085.0   2433.28